name: Flutter Web CI

# 1) Esto le dice a GitHub que ejecute el workflow en cada push a main
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 2) Saca tu código
      - name: Checkout repo
        uses: actions/checkout@v3

      # 3) Instala Flutter
      - name: Setup Flutter
        uses: actions/setup-flutter@v2
        with:
          flutter-version: 'stable'

      # 4) Obtiene dependencias
      - name: Install dependencies
        run: flutter pub get

      # 5) Genera la versión web
      - name: Build web
        run: flutter build web --release

      # 6) Publica en GitHub Pages
      - name: Deploy to Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
